// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhyyinuiaxtgdqukzuqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoeXlpbnVpYXh0Z2RxdWt6dXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDk3NDYsImV4cCI6MjA3MTQyNTc0Nn0.w0-LnQABbjGT3NBVI4qyGpT2Fa0Vbqm2iV_OyrlI-XU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});