// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://wgpevhrzbkmjkeryfrxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndncGV2aHJ6YmttamtlcnlmcnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODEwNDksImV4cCI6MjA2OTI1NzA0OX0.zIKkJHByod6BcCzY0ZT4DGo505x4iicsNwVRcXTBg5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});